# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Inno Setup
        run: |
          set -x
          sudo apt-get install -y -q innoextract
          sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32
          wine --version
          innoextract --version
          chmod +x ./gradle/innosetup/innoinstall.sh
          ./gradle/innosetup/innoinstall.sh
          sudo cp gradle/innosetup/iscc /usr/local/bin/iscc
          chmod +x gradle/innosetup/iscc
          gradle/innosetup/iscc
          echo "export PATH="$PATH:/gradle/innosetup/iscc" >> ~/.bash_profile
          source ~/.bash_profile

      - name: Build with Gradle
        run: ./gradlew build exe

      - name: Copy build distribution
        run: |
          cp build/distributions/*.zip cafe-distribution.zip
          cp build/innosetup/*.exe cafe.exe

      - name: Attach build distribution from this build
        uses: actions/upload-artifact@v2
        with:
          name: Cafe distribution from this build
          path: |
            ./cafe-distribution.zip
            ./cafe.exe

      - name: Create a release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Attach build distribution to the release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cafe-distribution.zip
          asset_name: cafe-distribution.zip
          asset_content_type: application/zip

      - name: Attach windows binary to the release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cafe.exe
          asset_name: cafe.exe
          asset_content_type: application/octet-stream
